services:
  frontend:
    image: node:14
    volumes:
      - ./:/app:cached
      - frontend_node_modules:/app/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn/v6
    ports:
      - 3001:3001
    working_dir: /app
    command: sh -c 'yarn && yarn run start'
    environment:
      REACT_APP_NODE_ENV: development
      PORT: 3001
volumes:
  frontend_node_modules: {}
  yarn_cache: {}
